name: Deploy (frontend)

on:
  workflow_call:

defaults:
  run:
    working-directory: frontend

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
      - name: Stage secrets for next deployment
        run: sops decrypt --output-type dotenv .env.enc | flyctl secrets import
      - name: Deploy frontend
        run: flyctl deploy --remote-only