name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  integrate-backend:
    name: Integrate (backend)
    secrets: inherit
    uses: ./.github/workflows/integrate-backend.yaml

  integrate-frontend:
    name: Integrate (frontend)
    uses: ./.github/workflows/integrate-frontend.yaml

  deploy-backend:
    concurrency: deploy-backend
    name: Deploy (backend)
    secrets: inherit
    needs: [integrate-backend, integrate-frontend]
    uses: ./.github/workflows/deploy-backend.yaml

  deploy-frontend:
    concurrency: deploy-frontend
    name: Deploy (frontend)
    secrets: inherit
    needs: [integrate-backend, integrate-frontend]
    uses: ./.github/workflows/deploy-frontend.yaml