name: Integrate

on:
  pull_request:
    branches: [ main ]

jobs:
  integrate-backend:
    name: Integrate (backend)
    uses: ./.github/workflows/integrate-backend.yaml

  integrate-frontend:
    name: Integrate (frontend)
    uses: ./.github/workflows/integrate-frontend.yaml